apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: unique-mandrill-go 
  janus-idp.io/tekton: unique-mandrill-go
  backstage.io/kubernetes-id: unique-mandrill-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: unique-mandrill-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  