apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: unique-mandrill-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unique-mandrill-go 
  name: unique-mandrill-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: unique-mandrill-go 
